package com.shinowit.framework.dao;

import com.shinowit.entity.TbaSupplyrecordinfo;
import com.shinowit.entity.TbaSupplyrecordinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaSupplyrecordinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int countByExample(TbaSupplyrecordinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int deleteByExample(TbaSupplyrecordinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int insert(TbaSupplyrecordinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int insertSelective(TbaSupplyrecordinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    List<TbaSupplyrecordinfo> selectByExample(TbaSupplyrecordinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    TbaSupplyrecordinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbaSupplyrecordinfo record, @Param("example") TbaSupplyrecordinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int updateByExample(@Param("record") TbaSupplyrecordinfo record, @Param("example") TbaSupplyrecordinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int updateByPrimaryKeySelective(TbaSupplyrecordinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    int updateByPrimaryKey(TbaSupplyrecordinfo record);

    List<TbaSupplyrecordinfo> selectPage(TbaSupplyrecordinfoCriteria example);

    Integer selectMaxPrimaryKeyValue();
}