package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class TbaSupplyrecordinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.ID
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.PayAccountNo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String payaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.PayBank
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String paybank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.RecAccountNo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String recaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.RecBank
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String recbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.Remark
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.SupplyTime
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String supplytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.TotalMoney
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private BigDecimal totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBa_SupplyRecordInfo.UserName
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.ID
     *
     * @return the value of TBa_SupplyRecordInfo.ID
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.ID
     *
     * @param id the value for TBa_SupplyRecordInfo.ID
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.PayAccountNo
     *
     * @return the value of TBa_SupplyRecordInfo.PayAccountNo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getPayaccountno() {
        return payaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.PayAccountNo
     *
     * @param payaccountno the value for TBa_SupplyRecordInfo.PayAccountNo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setPayaccountno(String payaccountno) {
        this.payaccountno = payaccountno == null ? null : payaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.PayBank
     *
     * @return the value of TBa_SupplyRecordInfo.PayBank
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getPaybank() {
        return paybank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.PayBank
     *
     * @param paybank the value for TBa_SupplyRecordInfo.PayBank
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setPaybank(String paybank) {
        this.paybank = paybank == null ? null : paybank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.RecAccountNo
     *
     * @return the value of TBa_SupplyRecordInfo.RecAccountNo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getRecaccountno() {
        return recaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.RecAccountNo
     *
     * @param recaccountno the value for TBa_SupplyRecordInfo.RecAccountNo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setRecaccountno(String recaccountno) {
        this.recaccountno = recaccountno == null ? null : recaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.RecBank
     *
     * @return the value of TBa_SupplyRecordInfo.RecBank
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getRecbank() {
        return recbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.RecBank
     *
     * @param recbank the value for TBa_SupplyRecordInfo.RecBank
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setRecbank(String recbank) {
        this.recbank = recbank == null ? null : recbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.Remark
     *
     * @return the value of TBa_SupplyRecordInfo.Remark
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.Remark
     *
     * @param remark the value for TBa_SupplyRecordInfo.Remark
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.SupplyTime
     *
     * @return the value of TBa_SupplyRecordInfo.SupplyTime
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getSupplytime() {
        return supplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.SupplyTime
     *
     * @param supplytime the value for TBa_SupplyRecordInfo.SupplyTime
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setSupplytime(String supplytime) {
        this.supplytime = supplytime == null ? null : supplytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.TotalMoney
     *
     * @return the value of TBa_SupplyRecordInfo.TotalMoney
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public BigDecimal getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.TotalMoney
     *
     * @param totalmoney the value for TBa_SupplyRecordInfo.TotalMoney
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setTotalmoney(BigDecimal totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBa_SupplyRecordInfo.UserName
     *
     * @return the value of TBa_SupplyRecordInfo.UserName
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBa_SupplyRecordInfo.UserName
     *
     * @param username the value for TBa_SupplyRecordInfo.UserName
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbaSupplyrecordinfo other = (TbaSupplyrecordinfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayaccountno() == null ? other.getPayaccountno() == null : this.getPayaccountno().equals(other.getPayaccountno()))
            && (this.getPaybank() == null ? other.getPaybank() == null : this.getPaybank().equals(other.getPaybank()))
            && (this.getRecaccountno() == null ? other.getRecaccountno() == null : this.getRecaccountno().equals(other.getRecaccountno()))
            && (this.getRecbank() == null ? other.getRecbank() == null : this.getRecbank().equals(other.getRecbank()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getSupplytime() == null ? other.getSupplytime() == null : this.getSupplytime().equals(other.getSupplytime()))
            && (this.getTotalmoney() == null ? other.getTotalmoney() == null : this.getTotalmoney().equals(other.getTotalmoney()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_SupplyRecordInfo
     *
     * @mbggenerated Tue Jan 06 09:25:24 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayaccountno() == null) ? 0 : getPayaccountno().hashCode());
        result = prime * result + ((getPaybank() == null) ? 0 : getPaybank().hashCode());
        result = prime * result + ((getRecaccountno() == null) ? 0 : getRecaccountno().hashCode());
        result = prime * result + ((getRecbank() == null) ? 0 : getRecbank().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getSupplytime() == null) ? 0 : getSupplytime().hashCode());
        result = prime * result + ((getTotalmoney() == null) ? 0 : getTotalmoney().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        return result;
    }
}